export const ALL_PERMISSION_CODES = [
  "org.logo",
  "org.name",
  "org.banner",
  "tariff",
  "charger.status",
  "charger.enable_disable",
  "charger.control",
  "notifications",
  "chargers.log",
  "schedule",
  "users.edit",
  "rfid.edit",
  "finance.reports",
  "shift.set",
  "shift.collection",
  "tickets.manage",
  "audit.view",
  "map.view",
  "organizations.view",
  "organizations.manage",
  "reports.view",
  "sessions.view",
  "settings.view",
  "stations.view",
  "support.view",
  "users.view",
  "users.manage",
  "rfid.view",
  "locations.view",
  "locations.manage",
  "chargers.view",
  "chargers.manage",
  "tariffs.manage",
  "tariffs.view",
  "bills.view",
  "bills.export",
  "dashboard.view",
  "wizard.setup",
  "wizard.delete",
  "connectors.view",
  "connectors.manage",
  "monitor.view",
  "rbac.manage",
  "global.access",
] as const;

export type PermissionCode = (typeof ALL_PERMISSION_CODES)[number];

export type PermissionsMap = Partial<Record<PermissionCode, "R" | "RW">>;

export const PERMISSION_LABELS: Record<PermissionCode, string> = {
  "org.logo": "Organization Logo",
  "org.name": "Organization Name",
  "org.banner": "Organization Banner",
  tariff: "Tariff Management",
  "charger.status": "Charger Status",
  "charger.enable_disable": "Enable / Disable Charger",
  "charger.control": "Charger Remote Control",
  notifications: "Notifications",
  "chargers.log": "Charger Logs",
  schedule: "Scheduling",
  "users.edit": "User Management",
  "rfid.edit": "RFID Management",
  "finance.reports": "Financial Reports",
  "shift.set": "Shift Settings",
  "shift.collection": "Shift Collection",
  "tickets.manage": "Support Tickets & Maintenance",
  "audit.view": "View audit logs",
  "map.view": "View map",
  "organizations.view": "View organizations",
  "organizations.manage": "Manage organizations",
  "reports.view": "View reports",
  "sessions.view": "View sessions",
  "settings.view": "View settings",
  "stations.view": "View stations",
  "support.view": "View support",
  "users.view": "View users",
  "users.manage": "Manage users",
  "rfid.view": "View RFID",
  "locations.view": "View locations",
  "locations.manage": "Manage locations",
  "chargers.view": "View chargers",
  "chargers.manage": "Manage chargers",
  "tariffs.manage": "Manage tariffs",
  "tariffs.view": "View tariffs",
  "bills.view": "View bills",
  "bills.export": "Export bills",
  "dashboard.view": "View dashboard home",
  "wizard.setup": "Use Setup Wizard",
  "wizard.delete": "Use Delete Wizard",
  "connectors.view": "View connectors",
  "connectors.manage": "Manage connectors",
  "monitor.view": "View live monitoring",
  "rbac.manage": "Manage roles & permissions",
  "global.access": "Global access",
};
